# Numpy

### NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data strcutures.

In [3]:
import numpy as np ## np is alias

## create array using numpy
## create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [10]:
# reshaping 1D array to 2D array

arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1,5)  ## 1 row and 5 column

array([[1, 2, 3, 4, 5]])

In [11]:
# 2D array

arr2 = np.array([[1, 2, 3, 4, 5]])
print(arr2.shape)

(1, 5)


In [12]:
# 2D array

arr2 = np.array([[1, 2, 3, 4, 5], [2, 4, 6, 7, 9]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 4 6 7 9]]
(2, 5)


In [14]:
np.arange(0, 10, 2) # first is start value 2nd is stop and 3rd is step size

array([0, 2, 4, 6, 8])

In [15]:
np.arange(0, 10, 2).reshape(5, 1) # converted 2D array here 5 rows 1 column 

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
## it will create 2D array with 3 rows 4 columns and all value 1
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## identity matrix
np.eye(3) ## created 3 cross 3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
## Attributes of numpy

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", arr)
print("Shape: ", arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size (number of elements): ", arr.size)
print("Data type: ", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Data type:  int64
Item size (in bytes):  8


In [22]:
### Numpy Vectorized Operation

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

### All operation will happen between elements of same index

### Element wise addition
print("Addition: ", arr1 + arr2)

### Element wise subtraction
print("Subtraction: ", arr1 - arr2)

### Element wise multiplication
print("Multiplication: ", arr1 * arr2)

### Element wise division
print("Division: ", arr1 / arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [23]:
## Universal Function

arr = np.array([2, 3, 4, 5, 6])

### All function will be applied index wise

## Square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sin
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [37]:
## array slicing and indexing

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array : \n", arr)
print()

print(arr[0][0])  ## indexing start with 0
print()
print(arr[0 : 2, 2:]) 
print()
print(arr[1:, 2:])
print()
print(arr[1:, 1 : 3])

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1

[[3 4]
 [7 8]]

[[ 7  8]
 [11 12]]

[[ 6  7]
 [10 11]]


In [38]:
## Modify array elements
arr[0, 0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [39]:
arr[1:] += 100
print(arr)

[[100   2   3   4]
 [105 106 107 108]
 [109 110 111 112]]


In [40]:
### Statistical concepts - Normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1, 2, 3, 4, 5])

## Calculate the mean and standard deviation
mean = np.mean(data)
stdDev = np.std(data)
print("Mean:", mean)
print("Standard Deviation", stdDev)

# Normalize the data
normalizeData = (data - mean) / stdDev
print("Normalized data: ", normalizeData)

Mean: 3.0
Standard Deviation 1.4142135623730951
Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [41]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean: ", mean)

# Median
median = np.median(data)
print("Median: ", median)

# Standard Deviation
stdDev = np.std(data)
print("Standard Deviation: ", stdDev)

# Variance
variance = np.var(data)
print("Variance: ", variance)

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [49]:
## Logical Operation

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(data[data > 5])  ## Array with elements greater than 5
print(data[(data > 5) & (data < 9)])

[ 6  7  8  9 10]
[6 7 8]
